# Generated by Django 5.2.3 on 2026-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follow_accounts_fo_followe_7c063a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
